version: "3.7"
services:
  snek:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs/:/bot/logs/
      - ./:/bot/:ro
    tty: true
    environment:
      SNEK_BOT_TOKEN: ${SNEK_BOT_TOKEN}
      SNEK_API_TOKEN: ${SNEK_API_TOKEN}
      SNEK_LOG_LEVEL: ${SNEK_LOG_LEVEL}
